# Generated by Django 4.2.2 on 2023-06-13 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
